### PR TITLE
use more namespaces to group bindings

### PR DESCRIPTION
**Pull request by usaoc**
Try to group some bindings relevant to namespaced annotations under corresponding namespaced namespaces.

### CODE REVIEW

**Comment by usaoc** [comment]
Opening to ask if people feel this is a good direction.

**Comment by mflatt** [comment]
This seems good to me. Not sure whether we should merge now or wait for a large group of backward-incompatible changes in the near future.

**Comment by usaoc** [comment]
Merging now is fine if no further objection arises.  This one comes with temporary aliases for backward compatibility, so it should be “less backward-incompatible.”

**Comment by mflatt** [comment]
I keep forgetting to reply here, but I agree that merging now is fine. (I had noticed compatibility bindings the first time around, but somehow that didn't sink in.)

**Pull request merged**
